/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** OneOf type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export interface paths {
  "/audit": {
    get: operations["listAudit"];
  };
  "/auth/login": {
    post: operations["login"];
  };
  "/auth/logout": {
    post: operations["logout"];
  };
  "/config/workspace/file": {
    get: operations["getConfigWorkspaceFile"];
    put: operations["saveConfigWorkspaceFile"];
  };
  "/config/workspace/repair-permissions": {
    post: operations["repairConfigWorkspacePermissions"];
  };
  "/config/workspace/tree": {
    get: operations["getConfigWorkspaceTree"];
  };
  "/docker/admin/daemon-config": {
    get: operations["getDockerAdminDaemonConfig"];
  };
  "/docker/admin/daemon-config/apply": {
    post: operations["applyDockerAdminDaemonConfig"];
  };
  "/docker/admin/daemon-config/validate": {
    post: operations["validateDockerAdminDaemonConfig"];
  };
  "/docker/admin/overview": {
    get: operations["getDockerAdminOverview"];
  };
  "/docker/registries": {
    get: operations["getDockerRegistryStatus"];
  };
  "/docker/registries/login": {
    post: operations["loginDockerRegistry"];
  };
  "/docker/registries/logout": {
    post: operations["logoutDockerRegistry"];
  };
  "/git/workspace/commit": {
    post: operations["commitGitWorkspace"];
  };
  "/git/workspace/diff": {
    get: operations["getGitWorkspaceDiff"];
  };
  "/git/workspace/push": {
    post: operations["pushGitWorkspace"];
  };
  "/git/workspace/status": {
    get: operations["getGitWorkspaceStatus"];
  };
  "/health": {
    /** @deprecated */
    get: operations["getHealth"];
  };
  "/host/metrics": {
    get: operations["getHostMetrics"];
  };
  "/host/overview": {
    get: operations["getHostOverview"];
  };
  "/host/stacklab-logs": {
    get: operations["getStacklabLogs"];
  };
  "/jobs/{jobId}": {
    get: operations["getJob"];
    parameters: {
      path: {
        jobId: components["parameters"]["JobId"];
      };
    };
  };
  "/jobs/{jobId}/cancel": {
    post: operations["cancelJob"];
    parameters: {
      path: {
        jobId: components["parameters"]["JobId"];
      };
    };
  };
  "/jobs/{jobId}/events": {
    get: operations["listJobEvents"];
    parameters: {
      path: {
        jobId: components["parameters"]["JobId"];
      };
    };
  };
  "/jobs/active": {
    get: operations["listActiveJobs"];
  };
  "/live": {
    get: operations["getLiveness"];
  };
  "/maintenance/image-updates": {
    get: operations["listImageUpdates"];
  };
  "/maintenance/image-updates/check": {
    post: operations["checkImageUpdates"];
  };
  "/maintenance/images": {
    get: operations["getMaintenanceImages"];
  };
  "/maintenance/networks": {
    get: operations["getMaintenanceNetworks"];
    post: operations["createMaintenanceNetwork"];
  };
  "/maintenance/networks/{name}": {
    delete: operations["deleteMaintenanceNetwork"];
  };
  "/maintenance/prune": {
    post: operations["runMaintenancePrune"];
  };
  "/maintenance/prune-preview": {
    get: operations["getMaintenancePrunePreview"];
  };
  "/maintenance/update-stacks": {
    post: operations["updateStacks"];
  };
  "/maintenance/volumes": {
    get: operations["getMaintenanceVolumes"];
    post: operations["createMaintenanceVolume"];
  };
  "/maintenance/volumes/{name}": {
    delete: operations["deleteMaintenanceVolume"];
  };
  "/meta": {
    get: operations["getMeta"];
  };
  "/ready": {
    get: operations["getReadiness"];
  };
  "/service/metrics": {
    /** @description Return bounded, process-local service activity metrics. Counters reset when Stacklab restarts. */
    get: operations["getServiceMetrics"];
  };
  "/session": {
    get: operations["getSession"];
  };
  "/settings/host": {
    get: operations["getHostSettings"];
    put: operations["updateHostSettings"];
  };
  "/settings/maintenance-schedules": {
    get: operations["getMaintenanceSchedules"];
    put: operations["updateMaintenanceSchedules"];
  };
  "/settings/notifications": {
    get: operations["getNotificationSettings"];
    put: operations["updateNotificationSettings"];
  };
  "/settings/notifications/test": {
    post: operations["sendNotificationTest"];
  };
  "/settings/password": {
    post: operations["updatePassword"];
  };
  "/stacklab/update/apply": {
    post: operations["applyStacklabUpdate"];
  };
  "/stacklab/update/overview": {
    get: operations["getStacklabUpdateOverview"];
  };
  "/stacks": {
    get: operations["listStacks"];
    post: operations["createStack"];
  };
  "/stacks/{stackId}": {
    get: operations["getStack"];
    delete: operations["deleteStack"];
    parameters: {
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
  };
  "/stacks/{stackId}/actions/{action}": {
    post: operations["runStackAction"];
    parameters: {
      path: {
        stackId: components["parameters"]["StackId"];
        action: components["parameters"]["StackAction"];
      };
    };
  };
  "/stacks/{stackId}/audit": {
    get: operations["listStackAudit"];
    parameters: {
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
  };
  "/stacks/{stackId}/definition": {
    get: operations["getStackDefinition"];
    put: operations["updateStackDefinition"];
    parameters: {
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
  };
  "/stacks/{stackId}/resolved-config": {
    get: operations["getResolvedConfig"];
    post: operations["previewResolvedConfig"];
    parameters: {
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
  };
  "/stacks/{stackId}/workspace/file": {
    get: operations["getStackWorkspaceFile"];
    put: operations["saveStackWorkspaceFile"];
    parameters: {
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
  };
  "/stacks/{stackId}/workspace/repair-permissions": {
    post: operations["repairStackWorkspacePermissions"];
    parameters: {
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
  };
  "/stacks/{stackId}/workspace/tree": {
    get: operations["getStackWorkspaceTree"];
    parameters: {
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
  };
  "/templates": {
    get: operations["listTemplates"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ActiveJobItem: {
      action: string;
      current_step?: components["schemas"]["ActiveJobStep"];
      id: string;
      latest_event?: components["schemas"]["ActiveJobLatestEvent"];
      /** @description HTTP request that started the job, when available. */
      request_id?: string;
      /** Format: date-time */
      requested_at: string;
      stack_id: string | null;
      /** Format: date-time */
      started_at?: string;
      state: components["schemas"]["JobState"];
      workflow?: components["schemas"]["ActiveJobWorkflow"];
    };
    ActiveJobLatestEvent: {
      data?: string;
      event: string;
      message?: string;
      step?: components["schemas"]["ActiveJobStep"];
      /** Format: date-time */
      timestamp: string;
    };
    ActiveJobsResponse: {
      items: components["schemas"]["ActiveJobItem"][];
      summary: components["schemas"]["ActiveJobSummary"];
    };
    ActiveJobStep: {
      action: string;
      index: number;
      target_stack_id?: string;
      total: number;
    };
    ActiveJobSummary: {
      active_count: number;
      cancel_requested_count: number;
      queued_count: number;
      running_count: number;
    };
    ActiveJobWorkflow: {
      steps: {
          action: string;
          state: components["schemas"]["JobState"];
          target_stack_id?: string;
        }[];
    };
    /** @enum {string} */
    ActivityState: "idle" | "locked";
    AuditEntry: {
      action: string;
      duration_ms: number | null;
      /** Format: date-time */
      finished_at: string | null;
      id: string;
      job_id: string | null;
      /** Format: date-time */
      requested_at: string;
      requested_by: string;
      result: string;
      stack_id: string | null;
    };
    AuditListResponse: {
      items: components["schemas"]["AuditEntry"][];
      next_cursor: string | null;
    };
    ComposeWarning: {
      code: string;
      message: string;
      service?: string;
    };
    /** @enum {string} */
    ConfigEntryType: "directory" | "text_file" | "binary_file" | "unknown_file";
    ConfigFileResponse: {
      blocked_reason: string | null;
      content: string | null;
      encoding: string | null;
      git_ignored: boolean;
      /** Format: date-time */
      modified_at: string;
      name: string;
      path: string;
      permissions: components["schemas"]["FilePermissions"];
      readable: boolean;
      repair_capability: components["schemas"]["WorkspaceRepairCapability"];
      size_bytes: number;
      stack_id: string | null;
      type: components["schemas"]["ConfigEntryType"];
      writable: boolean;
    };
    ConfigFileSaveRequest: {
      content: string;
      create_parent_directories: boolean;
      /** Format: date-time */
      expected_modified_at?: string | null;
      path: string;
    };
    ConfigFileSaveResponse: {
      audit_action: string;
      /** Format: date-time */
      modified_at: string;
      path: string;
      saved: boolean;
    };
    ConfigRepairPermissionsRequest: {
      path: string;
      /** @default false */
      recursive?: boolean;
    };
    ConfigRepairPermissionsResponse: {
      audit_action: string;
      changed_items: number;
      path: string;
      recursive: boolean;
      repair_capability: components["schemas"]["WorkspaceRepairCapability"];
      repaired: boolean;
      target_permissions_after: components["schemas"]["FilePermissions"];
      target_permissions_before: components["schemas"]["FilePermissions"];
      warnings?: string[];
    };
    /** @enum {string} */
    ConfigState: "unknown" | "in_sync" | "drifted" | "invalid";
    ConfigTreeEntry: {
      git_ignored: boolean;
      /** Format: date-time */
      modified_at: string;
      name: string;
      path: string;
      permissions: components["schemas"]["FilePermissions"];
      size_bytes: number;
      stack_id: string | null;
      type: components["schemas"]["ConfigEntryType"];
    };
    ConfigTreeResponse: {
      current_path: string;
      items: components["schemas"]["ConfigTreeEntry"][];
      parent_path: string | null;
      workspace_root: string;
    };
    Container: {
      health_status: string | null;
      id: string;
      image_id: string;
      image_ref: string;
      name: string;
      networks: string[];
      ports: components["schemas"]["PortMapping"][];
      service_name: string;
      /** Format: date-time */
      started_at: string | null;
      status: components["schemas"]["ContainerStatus"];
    };
    /** @enum {string} */
    ContainerStatus: "created" | "running" | "restarting" | "paused" | "exited" | "dead";
    CreateStackRequest: {
      compose_yaml?: string;
      create_config_dir: boolean;
      create_data_dir: boolean;
      deploy_after_create: boolean;
      env: string;
      stack_id: string;
      template_id?: string;
      variables?: {
        [key: string]: string;
      };
    };
    DefinitionRevision: {
      /** Format: date-time */
      compose_modified_at: string;
      /** Format: date-time */
      env_modified_at: string | null;
    };
    DeleteStackRequest: {
      remove_config: boolean;
      remove_data: boolean;
      remove_definition: boolean;
      remove_runtime: boolean;
    };
    /** @enum {string} */
    DisplayState: "defined" | "running" | "partial" | "stopped" | "error" | "orphaned";
    DockerAdminOverviewResponse: {
      daemon_config: components["schemas"]["DockerDaemonConfigMeta"];
      engine: components["schemas"]["DockerEngineStatus"];
      service: components["schemas"]["DockerServiceStatus"];
      write_capability: components["schemas"]["DockerDaemonWriteCapability"];
    };
    DockerDaemonConfigMeta: {
      configured_keys: string[];
      exists: boolean;
      /** Format: date-time */
      modified_at?: string | null;
      parse_error?: string | null;
      path: string;
      permissions?: components["schemas"]["FilePermissionsNullable"];
      size_bytes?: number | null;
      summary: components["schemas"]["DockerDaemonConfigSummary"];
      valid_json: boolean;
      write_capability: components["schemas"]["DockerDaemonWriteCapability"];
    };
    DockerDaemonConfigPreview: {
      configured_keys: string[];
      content: string;
      path: string;
      summary: components["schemas"]["DockerDaemonConfigSummary"];
    };
    DockerDaemonConfigResponse: components["schemas"]["DockerDaemonConfigMeta"] & ({
      content?: string | null;
    });
    DockerDaemonConfigSummary: {
      data_root: string;
      dns: string[];
      insecure_registries: string[];
      live_restore?: boolean | null;
      log_driver: string;
      registry_mirrors: string[];
    };
    DockerDaemonValidateRequest: {
      remove_keys?: string[];
      settings: components["schemas"]["DockerManagedSettings"];
    };
    DockerDaemonValidateResponse: {
      changed_keys: string[];
      preview: components["schemas"]["DockerDaemonConfigPreview"];
      requires_restart: boolean;
      warnings: string[];
      write_capability: components["schemas"]["DockerDaemonWriteCapability"];
    };
    DockerDaemonWriteCapability: {
      managed_keys: string[];
      reason?: string | null;
      supported: boolean;
    };
    DockerEngineStatus: {
      api_version: string;
      available: boolean;
      cgroup_driver: string;
      compose_version: string;
      driver: string;
      logging_driver: string;
      message?: string | null;
      root_dir: string;
      version: string;
    };
    DockerManagedSettings: {
      dns?: string[];
      insecure_registries?: string[];
      live_restore?: boolean;
      registry_mirrors?: string[];
    };
    DockerMeta: {
      compose_version: string;
      engine_version: string;
    };
    DockerRegistryEntry: {
      configured: boolean;
      last_error: string;
      /** Format: date-time */
      last_verified_at?: string | null;
      registry: string;
      source: string;
      username: string;
    };
    DockerRegistryLoginRequest: {
      password: string;
      registry: string;
      username: string;
    };
    DockerRegistryLogoutRequest: {
      registry: string;
    };
    DockerRegistryStatusResponse: {
      docker_config_path: string;
      exists: boolean;
      items: components["schemas"]["DockerRegistryEntry"][];
      /** Format: date-time */
      modified_at?: string | null;
      parse_error?: string | null;
      permissions?: components["schemas"]["FilePermissionsNullable"];
      size_bytes?: number | null;
      valid_json: boolean;
    };
    DockerServiceStatus: {
      active_state: string;
      fragment_path: string;
      load_state: string;
      manager: string;
      message?: string | null;
      /** Format: date-time */
      started_at?: string | null;
      sub_state: string;
      supported: boolean;
      unit_file_state: string;
      unit_name: string;
    };
    EmptyObject: Record<string, never>;
    ErrorDetail: {
      code: string;
      details?: Record<string, never> | null;
      message: string;
    };
    ErrorResponse: {
      error: components["schemas"]["ErrorDetail"];
    };
    FeatureFlags: {
      host_shell: boolean;
    };
    FilePermissions: {
      group_gid?: number | null;
      group_name?: string | null;
      mode: string;
      owner_name?: string | null;
      owner_uid?: number | null;
      readable: boolean;
      writable: boolean;
    };
    FilePermissionsNullable: components["schemas"]["FilePermissions"] | null;
    GitCommitRequest: {
      message: string;
      paths: string[];
    };
    GitCommitResponse: {
      commit: string;
      committed: boolean;
      paths: string[];
      remaining_changes: number;
      summary: string;
    };
    GitDiffResponse: {
      available: boolean;
      blocked_reason?: string | null;
      diff?: string | null;
      diff_available: boolean;
      is_binary: boolean;
      old_path?: string | null;
      path: string;
      permissions?: components["schemas"]["FilePermissionsNullable"];
      scope: components["schemas"]["GitScope"];
      stack_id?: string | null;
      status: components["schemas"]["GitFileStatus"];
      truncated: boolean;
    };
    /** @enum {string} */
    GitFileStatus: "modified" | "added" | "deleted" | "renamed" | "untracked" | "conflicted";
    GitPushResponse: {
      ahead_count: number;
      behind_count: number;
      branch: string;
      head_commit: string;
      pushed: boolean;
      remote: string;
      upstream_name: string;
    };
    /** @enum {string} */
    GitScope: "stacks" | "config";
    GitStatusItem: {
      blocked_reason?: string | null;
      commit_allowed: boolean;
      diff_available: boolean;
      old_path?: string | null;
      path: string;
      permissions?: components["schemas"]["FilePermissionsNullable"];
      scope: components["schemas"]["GitScope"];
      stack_id?: string | null;
      status: components["schemas"]["GitFileStatus"];
    };
    GitWorkspaceStatusResponse: {
      ahead_count?: number;
      available: boolean;
      behind_count?: number;
      branch?: string;
      clean?: boolean;
      has_upstream?: boolean;
      head_commit?: string;
      items?: components["schemas"]["GitStatusItem"][];
      managed_roots: string[];
      reason?: string;
      repo_root: string;
      upstream_name?: string;
    };
    HealthCheckResponse: {
      message?: string;
      /** @enum {string} */
      status: "ok" | "error";
    };
    HealthResponse: {
      checks: {
        [key: string]: components["schemas"]["HealthCheckResponse"];
      };
      /** @enum {string} */
      status: "ok" | "unavailable";
      version: string;
    };
    HealthSummary: {
      healthy_container_count: number;
      unhealthy_container_count: number;
      unknown_health_container_count: number;
    };
    HostCPU: {
      core_count: number;
      load_average: number[];
      /** Format: double */
      usage_percent: number;
    };
    HostDisk: {
      available_bytes: number;
      path: string;
      total_bytes: number;
      /** Format: double */
      usage_percent: number;
      used_bytes: number;
    };
    HostDiskIO: {
      devices: components["schemas"]["HostDiskIODevice"][];
      /** Format: double */
      total_read_bytes_per_sec: number;
      /** Format: double */
      total_write_bytes_per_sec: number;
    };
    HostDiskIODevice: {
      name: string;
      /** Format: int64 */
      read_bytes: number;
      /** Format: double */
      read_bytes_per_sec: number;
      /** Format: int64 */
      write_bytes: number;
      /** Format: double */
      write_bytes_per_sec: number;
    };
    HostFilesystem: {
      /** Format: int64 */
      available_bytes: number;
      device: string;
      fs_type: string;
      mount_point: string;
      primary: boolean;
      /** Format: int64 */
      total_bytes: number;
      /** Format: double */
      usage_percent: number;
      /** Format: int64 */
      used_bytes: number;
    };
    HostMemory: {
      available_bytes: number;
      total_bytes: number;
      /** Format: double */
      usage_percent: number;
      used_bytes: number;
    };
    HostMeta: {
      architecture: string;
      hostname: string;
      kernel_version: string;
      os_name: string;
      uptime_seconds: number;
    };
    HostMetricSample: {
      cpu: components["schemas"]["HostCPU"];
      disk_io: components["schemas"]["HostDiskIO"];
      filesystems: components["schemas"]["HostFilesystem"][];
      memory: components["schemas"]["HostMemory"];
      network: components["schemas"]["HostNetwork"];
      processes?: components["schemas"]["HostProcesses"];
      /** Format: date-time */
      sampled_at: string;
      swap: components["schemas"]["HostSwap"];
      temperatures: components["schemas"]["HostTemperatures"];
    };
    HostMetricsResponse: {
      active_sample_interval_seconds: number;
      background_sample_interval_seconds: number;
      current: components["schemas"]["HostMetricSample"] | null;
      history: components["schemas"]["HostMetricSample"][];
      history_window_seconds: number;
      sample_interval_seconds: number;
    };
    HostNetwork: {
      interfaces: components["schemas"]["HostNetworkInterface"][];
      public_ip?: string;
      /** Format: double */
      total_rx_bytes_per_sec: number;
      /** Format: double */
      total_tx_bytes_per_sec: number;
    };
    HostNetworkInterface: {
      name: string;
      /** Format: int64 */
      rx_bytes: number;
      /** Format: double */
      rx_bytes_per_sec: number;
      /** Format: int64 */
      tx_bytes: number;
      /** Format: double */
      tx_bytes_per_sec: number;
    };
    HostOverviewResponse: {
      docker: components["schemas"]["DockerMeta"];
      host: components["schemas"]["HostMeta"];
      resources: components["schemas"]["HostResources"];
      stacklab: components["schemas"]["StacklabMeta"];
    };
    HostProcess: {
      command: string;
      container?: components["schemas"]["HostProcessContainer"];
      /** Format: double */
      cpu_percent: number;
      display_command?: string;
      /** Format: int64 */
      memory_bytes: number;
      /** Format: double */
      memory_percent: number;
      pid: number;
      state: string;
      user: string;
    };
    HostProcessContainer: {
      id: string;
      name?: string;
      service_name?: string;
      stack_id?: string;
    };
    HostProcesses: {
      items: components["schemas"]["HostProcess"][];
      total: number;
    };
    HostResources: {
      cpu: components["schemas"]["HostCPU"];
      disk: components["schemas"]["HostDisk"];
      memory: components["schemas"]["HostMemory"];
    };
    HostSettingsRequest: {
      public_ip_lookup_enabled: boolean;
    };
    HostSettingsResponse: components["schemas"]["HostSettingsRequest"];
    HostSwap: {
      /** Format: int64 */
      available_bytes: number;
      /** Format: int64 */
      total_bytes: number;
      /** Format: double */
      usage_percent: number;
      /** Format: int64 */
      used_bytes: number;
    };
    HostTemperatures: {
      /** Format: double */
      cpu_celsius: number | null;
      cpu_sensor?: components["schemas"]["HostTemperatureSensor"] | null;
      sensors: components["schemas"]["HostTemperatureSensor"][];
    };
    HostTemperatureSensor: {
      label: string;
      name: string;
      /** Format: double */
      temperature_celsius: number;
    };
    ImageUpdatesResponse: {
      items: components["schemas"]["ImageUpdateStatus"][];
    };
    ImageUpdateStatus: {
      /** Format: date-time */
      checked_at: string;
      image_ref: string;
      local_digest?: string;
      remote_digest?: string;
      /** @enum {string} */
      state: "available" | "up_to_date" | "unknown";
    };
    Job: {
      action: string;
      /** Format: date-time */
      finished_at?: string;
      id: string;
      /** @description HTTP request that started the job, when available. */
      request_id?: string;
      /** Format: date-time */
      requested_at: string;
      stack_id: string | null;
      /** Format: date-time */
      started_at?: string;
      state: components["schemas"]["JobState"];
      workflow?: {
        steps: {
            action: string;
            state: components["schemas"]["JobState"];
            target_service_names?: string[];
            target_stack_id?: string;
          }[];
      };
    };
    JobDetailResponse: {
      job: components["schemas"]["Job"];
    };
    JobEnvelopeResponse: {
      job: components["schemas"]["Job"];
    };
    JobEventRecord: {
      data?: string;
      event: string;
      job_id: string;
      message?: string;
      progress?: components["schemas"]["JobProgress"];
      sequence: number;
      state: components["schemas"]["JobState"];
      step?: components["schemas"]["ActiveJobStep"];
      /** Format: date-time */
      timestamp: string;
    };
    JobEventsResponse: {
      items: components["schemas"]["JobEventRecord"][];
      job_id: string;
      message?: string;
      retained: boolean;
    };
    JobProgress: {
      completed: number;
      detail?: string;
      phase: string;
      total: number;
      unit: string;
    };
    /** @enum {string} */
    JobState: "queued" | "running" | "succeeded" | "failed" | "cancel_requested" | "cancelled" | "timed_out";
    /** @enum {string} */
    JobStateTerminal: "succeeded" | "failed" | "cancelled" | "timed_out";
    LastAction: {
      action: string;
      /** Format: date-time */
      finished_at: string;
      result: components["schemas"]["JobStateTerminal"];
    } | null;
    LivenessResponse: {
      /** @constant */
      status: "ok";
      version: string;
    };
    LoginRequest: {
      password: string;
    };
    LoginResponse: {
      /** @constant */
      authenticated: true;
    };
    LogoutResponse: {
      /** @constant */
      authenticated: false;
    };
    MaintenanceCreateNetworkRequest: {
      name: string;
    };
    MaintenanceCreateNetworkResponse: {
      created: boolean;
      name: string;
    };
    MaintenanceCreateVolumeRequest: {
      name: string;
    };
    MaintenanceCreateVolumeResponse: {
      created: boolean;
      name: string;
    };
    MaintenanceDeleteNetworkResponse: {
      deleted: boolean;
      name: string;
    };
    MaintenanceDeleteVolumeResponse: {
      deleted: boolean;
      name: string;
    };
    MaintenanceImageItem: {
      containers_using: number;
      /** Format: date-time */
      created_at: string;
      id: string;
      is_dangling: boolean;
      is_unused: boolean;
      reference: string;
      repository: string;
      size_bytes: number;
      /** @enum {string} */
      source: "stack_managed" | "external";
      stacks_using: components["schemas"]["MaintenanceImageStackUsage"][];
      tag: string;
    };
    MaintenanceImagesResponse: {
      items: components["schemas"]["MaintenanceImageItem"][];
    };
    MaintenanceImageStackUsage: {
      service_names: string[];
      stack_id: string;
    };
    MaintenanceNetworkItem: {
      attachable: boolean;
      containers_using: number;
      driver: string;
      id: string;
      ingress: boolean;
      internal: boolean;
      is_unused: boolean;
      name: string;
      scope: string;
      /** @enum {string} */
      source: "stack_managed" | "external";
      stacks_using: components["schemas"]["MaintenanceImageStackUsage"][];
    };
    MaintenanceNetworksResponse: {
      items: components["schemas"]["MaintenanceNetworkItem"][];
    };
    MaintenancePrunePreview: {
      build_cache: components["schemas"]["MaintenancePrunePreviewCategory"];
      images: components["schemas"]["MaintenancePrunePreviewCategory"];
      stopped_containers: components["schemas"]["MaintenancePrunePreviewCategory"];
      total_reclaimable_bytes: number;
      volumes: components["schemas"]["MaintenancePrunePreviewCategory"];
    };
    MaintenancePrunePreviewCategory: {
      count: number;
      items?: components["schemas"]["MaintenancePrunePreviewItem"][];
      reclaimable_bytes: number;
    };
    MaintenancePrunePreviewItem: {
      reason: string;
      reference: string;
      size_bytes: number;
    };
    MaintenancePrunePreviewResponse: {
      preview: components["schemas"]["MaintenancePrunePreview"];
    };
    MaintenancePruneRequest: {
      scope: components["schemas"]["MaintenancePruneScope"];
    };
    MaintenancePruneScheduleConfig: {
      enabled: boolean;
      frequency: components["schemas"]["MaintenanceScheduleFrequency"];
      scope: components["schemas"]["MaintenancePruneScope"];
      time: string;
      weekdays?: components["schemas"]["MaintenanceScheduleWeekday"][];
    };
    MaintenancePruneSchedulePolicy: components["schemas"]["MaintenancePruneScheduleConfig"] & {
      status: components["schemas"]["MaintenanceScheduleStatus"];
    };
    MaintenancePruneScope: {
      build_cache: boolean;
      images: boolean;
      stopped_containers: boolean;
      volumes: boolean;
    };
    /** @enum {string} */
    MaintenanceScheduleFrequency: "daily" | "weekly";
    MaintenanceSchedulesRequest: {
      prune: components["schemas"]["MaintenancePruneScheduleConfig"];
      update: components["schemas"]["MaintenanceUpdateScheduleConfig"];
    };
    MaintenanceSchedulesResponse: {
      prune: components["schemas"]["MaintenancePruneSchedulePolicy"];
      timezone: string;
      update: components["schemas"]["MaintenanceUpdateSchedulePolicy"];
    };
    MaintenanceScheduleStatus: {
      last_job_id?: string;
      last_message?: string;
      /** @enum {string} */
      last_result?: "running" | "succeeded" | "failed" | "skipped";
      /** Format: date-time */
      last_scheduled_for?: string;
      /** Format: date-time */
      last_triggered_at?: string;
      /** Format: date-time */
      next_run_at?: string;
    };
    /** @enum {string} */
    MaintenanceScheduleWeekday: "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";
    MaintenanceUpdateScheduleConfig: {
      enabled: boolean;
      frequency: components["schemas"]["MaintenanceScheduleFrequency"];
      options: {
        build_images: boolean;
        include_volumes: boolean;
        prune_after: boolean;
        pull_images: boolean;
        remove_orphans: boolean;
      };
      target: {
        excluded_services?: {
          [key: string]: string[];
        };
        /** @enum {string} */
        mode: "selected" | "all";
        stack_ids?: string[];
      };
      time: string;
      weekdays?: components["schemas"]["MaintenanceScheduleWeekday"][];
    };
    MaintenanceUpdateSchedulePolicy: components["schemas"]["MaintenanceUpdateScheduleConfig"] & {
      status: components["schemas"]["MaintenanceScheduleStatus"];
    };
    MaintenanceUpdateStacksRequest: {
      options?: {
        /** @default true */
        build_images?: boolean;
        prune_after?: {
          /** @default false */
          enabled?: boolean;
          /** @default false */
          include_volumes?: boolean;
        };
        /** @default true */
        pull_images?: boolean;
        /** @default true */
        remove_orphans?: boolean;
      };
      target: {
        excluded_services?: {
          [key: string]: string[];
        };
        /** @enum {string} */
        mode: "selected" | "all";
        stack_ids?: string[];
      };
    };
    MaintenanceVolumeItem: {
      containers_using: number;
      driver: string;
      is_unused: boolean;
      mountpoint: string;
      name: string;
      options_count: number;
      scope: string;
      /** @enum {string} */
      source: "stack_managed" | "external";
      stacks_using: components["schemas"]["MaintenanceImageStackUsage"][];
    };
    MaintenanceVolumesResponse: {
      items: components["schemas"]["MaintenanceVolumeItem"][];
    };
    MetaResponse: {
      app: {
        name: string;
        version: string;
      };
      docker: {
        compose_version: string;
        engine_version: string;
      };
      environment: {
        platform: string;
        stack_root: string;
      };
      features: components["schemas"]["FeatureFlags"];
    };
    NotificationChannelsRequest: {
      telegram?: components["schemas"]["NotificationTelegramChannelRequest"];
      webhook?: components["schemas"]["NotificationWebhookChannelRequest"];
    };
    NotificationChannelsResponse: {
      telegram: components["schemas"]["NotificationTelegramChannel"];
      webhook: components["schemas"]["NotificationWebhookChannel"];
    };
    NotificationEventToggles: {
      job_failed: boolean;
      job_succeeded_with_warnings: boolean;
      maintenance_succeeded: boolean;
      post_update_recovery_failed?: boolean;
      runtime_health_degraded?: boolean;
      runtime_log_error_burst?: boolean;
      stacklab_service_error?: boolean;
    };
    NotificationSettingsRequest: {
      channels?: components["schemas"]["NotificationChannelsRequest"];
      enabled: boolean;
      events: components["schemas"]["NotificationEventToggles"];
      webhook_url: string;
    };
    NotificationSettingsResponse: {
      channels: components["schemas"]["NotificationChannelsResponse"];
      configured: boolean;
      enabled: boolean;
      events: components["schemas"]["NotificationEventToggles"];
      webhook_url: string;
    };
    NotificationTelegramChannel: {
      bot_token_configured: boolean;
      chat_id: string;
      configured: boolean;
      enabled: boolean;
    };
    NotificationTelegramChannelRequest: {
      bot_token: string;
      chat_id: string;
      enabled: boolean;
    };
    NotificationTestRequest: {
      /** @enum {string} */
      channel?: "webhook" | "telegram";
      channels?: components["schemas"]["NotificationChannelsRequest"];
      enabled: boolean;
      events: components["schemas"]["NotificationEventToggles"];
      webhook_url: string;
    };
    NotificationTestResponse: {
      /** @enum {string} */
      channel: "webhook" | "telegram";
      sent: boolean;
    };
    NotificationWebhookChannel: {
      configured: boolean;
      enabled: boolean;
      url: string;
    };
    NotificationWebhookChannelRequest: {
      enabled: boolean;
      url: string;
    };
    PortMapping: {
      protocol: string;
      published: number;
      target: number;
    };
    ResolvedConfigPreviewRequest: {
      compose_yaml: string;
      env: string;
    };
    ResolvedConfigResponse: OneOf<[{
      content: string;
      stack_id: string;
      /** @constant */
      valid: true;
      warnings?: components["schemas"]["ComposeWarning"][];
    }, {
      error: components["schemas"]["ErrorDetail"];
      stack_id: string;
      /** @constant */
      valid: false;
      warnings?: components["schemas"]["ComposeWarning"][];
    }]>;
    /** @enum {string} */
    RuntimeState: "defined" | "running" | "partial" | "stopped" | "error" | "orphaned";
    Service: {
      build_context: string | null;
      depends_on: string[];
      dockerfile_path: string | null;
      healthcheck_present: boolean;
      image_ref: string | null;
      mode: components["schemas"]["ServiceMode"];
      name: string;
      ports: components["schemas"]["PortMapping"][];
      volumes: components["schemas"]["VolumeMount"][];
    };
    ServiceHTTPMetrics: {
      /** Format: double */
      duration_seconds_max: number;
      /** Format: double */
      duration_seconds_total: number;
      errors_total: number;
      requests_in_flight: number;
      requests_total: number;
    };
    ServiceJobMetrics: {
      active: number;
      completed_total: number;
      /** Format: double */
      duration_seconds_max: number;
      /** Format: double */
      duration_seconds_total: number;
      errors_total: number;
      started_total: number;
    };
    ServiceMetricsResponse: {
      /** Format: date-time */
      collected_at: string;
      http: components["schemas"]["ServiceHTTPMetrics"];
      jobs: components["schemas"]["ServiceJobMetrics"];
      process: components["schemas"]["ServiceProcessMetrics"];
      readiness: components["schemas"]["ServiceReadinessMetrics"];
      websockets: components["schemas"]["ServiceWebSocketMetrics"];
    };
    /** @enum {string} */
    ServiceMode: "image" | "build" | "hybrid";
    ServiceProcessMetrics: {
      /** Format: date-time */
      started_at: string;
      uptime_seconds: number;
    };
    ServiceReadinessMetrics: {
      /** Format: date-time */
      checked_at: string | null;
      checks: {
        [key: string]: "ok" | "error";
      };
      /** @enum {string} */
      status: "unknown" | "ok" | "unavailable";
    };
    ServiceWebSocketMetrics: {
      /** Format: double */
      connection_duration_seconds_max: number;
      /** Format: double */
      connection_duration_seconds_total: number;
      connections_active: number;
      connections_total: number;
      errors_total: number;
    };
    SessionResponse: {
      authenticated: boolean;
      features: components["schemas"]["FeatureFlags"];
      user?: components["schemas"]["SessionUser"];
    };
    SessionUser: {
      display_name: string;
      id: string;
    };
    StackCapabilities: {
      can_edit_definition: boolean;
      can_open_terminal: boolean;
      can_view_logs: boolean;
      can_view_stats: boolean;
    };
    StackDefinitionResponse: {
      config_state: components["schemas"]["ConfigState"];
      files: {
        compose_yaml: {
          content: string;
          /** Format: date-time */
          modified_at: string;
          path: string;
        };
        env: {
          content: string;
          exists: boolean;
          /** Format: date-time */
          modified_at: string | null;
          path: string;
        };
      };
      stack_id: string;
    };
    StackDetail: components["schemas"]["StackHeader"] & ({
      available_actions: string[];
      capabilities: components["schemas"]["StackCapabilities"];
      compose_file_path: string;
      config_path: string;
      containers: components["schemas"]["Container"][];
      data_path: string;
      env_file_path: string;
      last_action: components["schemas"]["LastAction"];
      /** Format: date-time */
      last_deployed_at: string | null;
      root_path: string;
      services: components["schemas"]["Service"][];
      updates: components["schemas"]["StackUpdates"];
    });
    StackDetailResponse: {
      stack: components["schemas"]["StackDetail"];
    };
    StackHeader: {
      activity_state: components["schemas"]["ActivityState"];
      config_state: components["schemas"]["ConfigState"];
      /** Format: date-time */
      created_at: string;
      display_state: components["schemas"]["DisplayState"];
      health_summary: components["schemas"]["HealthSummary"];
      id: string;
      metadata: components["schemas"]["StackMetadata"];
      name: string;
      runtime_state: components["schemas"]["RuntimeState"];
      /** Format: date-time */
      updated_at: string;
    };
    StacklabLogEntry: {
      cursor: string;
      /** @enum {string} */
      level: "debug" | "info" | "warn" | "error";
      message: string;
      /** Format: date-time */
      timestamp: string;
    };
    StacklabLogsResponse: {
      has_more: boolean;
      items: components["schemas"]["StacklabLogEntry"][];
      next_cursor?: string | null;
    };
    StacklabMeta: {
      commit: string;
      /** Format: date-time */
      started_at: string;
      version: string;
    };
    StacklabUpdateApplyRequest: {
      expected_candidate_version?: string;
      refresh_package_index?: boolean;
    };
    StacklabUpdateApplyResponse: {
      job: components["schemas"]["Job"];
      package: components["schemas"]["StacklabUpdatePackageStatus"];
      runtime?: components["schemas"]["StacklabUpdateRuntimeStatus"];
      started: boolean;
    };
    StacklabUpdateOverviewResponse: {
      current_version: string;
      install_mode: string;
      package: components["schemas"]["StacklabUpdatePackageStatus"];
      runtime?: components["schemas"]["StacklabUpdateRuntimeStatus"];
      write_capability: components["schemas"]["StacklabUpdateWriteCapability"];
    };
    StacklabUpdatePackageStatus: {
      candidate_version?: string;
      configured_channel?: string;
      installed_version?: string;
      message?: string;
      name: string;
      supported: boolean;
      update_available: boolean;
    };
    StacklabUpdateRuntimeStatus: {
      /** Format: date-time */
      finished_at?: string | null;
      installed_version?: string;
      job_id?: string;
      message?: string;
      pending_finalize: boolean;
      requested_version?: string;
      result?: string;
      /** Format: date-time */
      started_at?: string | null;
    };
    StacklabUpdateWriteCapability: {
      reason?: string;
      supported: boolean;
    };
    StackListItem: components["schemas"]["StackHeader"] & {
      last_action: components["schemas"]["LastAction"];
      service_count: {
        defined: number;
        running: number;
      };
      stats: components["schemas"]["StackStats"];
      updates: components["schemas"]["StackUpdates"];
    };
    StackListResponse: {
      items: components["schemas"]["StackListItem"][];
      summary: components["schemas"]["StackListSummary"];
    };
    StackListSummary: {
      container_count: {
        running: number;
        total: number;
      };
      defined_count: number;
      error_count: number;
      orphaned_count: number;
      running_count: number;
      stack_count: number;
      stopped_count: number;
    };
    StackMetadata: {
      icon?: string;
      links?: {
          label: string;
          url: string;
        }[];
    } | null;
    StackRepairPermissionsRequest: {
      path: string;
      /** @default false */
      recursive?: boolean;
    };
    StackRepairPermissionsResponse: {
      audit_action: string;
      changed_items: number;
      path: string;
      recursive: boolean;
      repair_capability: components["schemas"]["WorkspaceRepairCapability"];
      repaired: boolean;
      stack_id: string;
      target_permissions_after: components["schemas"]["FilePermissions"];
      target_permissions_before: components["schemas"]["FilePermissions"];
      warnings?: string[];
    };
    StackStats: {
      cpu_percent: number;
      memory_bytes: number;
      /** Format: date-time */
      sampled_at: string;
    } | null;
    StackTemplate: {
      built_in: boolean;
      compose_yaml: string;
      description?: string;
      icon?: string;
      id: string;
      name: string;
      variables?: components["schemas"]["TemplateVariable"][];
    };
    StackUpdates: ({
      /** Format: date-time */
      checked_at: string;
      services_with_updates: number;
      /** @enum {string} */
      state: "available" | "up_to_date" | "unknown";
    }) | null;
    StackWorkspaceFileResponse: {
      blocked_reason: string | null;
      content: string | null;
      encoding: string | null;
      /** Format: date-time */
      modified_at: string;
      name: string;
      path: string;
      permissions: components["schemas"]["FilePermissions"];
      readable: boolean;
      repair_capability: components["schemas"]["WorkspaceRepairCapability"];
      size_bytes: number;
      stack_id: string;
      type: components["schemas"]["ConfigEntryType"];
      writable: boolean;
    };
    StackWorkspaceFileSaveRequest: {
      content: string;
      create_parent_directories: boolean;
      /** Format: date-time */
      expected_modified_at?: string | null;
      path: string;
    };
    StackWorkspaceFileSaveResponse: {
      audit_action: string;
      /** Format: date-time */
      modified_at: string;
      path: string;
      saved: boolean;
      stack_id: string;
    };
    StackWorkspaceTreeEntry: {
      /** Format: date-time */
      modified_at: string;
      name: string;
      path: string;
      permissions: components["schemas"]["FilePermissions"];
      size_bytes: number;
      type: components["schemas"]["ConfigEntryType"];
    };
    StackWorkspaceTreeResponse: {
      current_path: string;
      items: components["schemas"]["StackWorkspaceTreeEntry"][];
      parent_path: string | null;
      stack_id: string;
      workspace_root: string;
    };
    TemplatesResponse: {
      items: components["schemas"]["StackTemplate"][];
    };
    TemplateVariable: {
      default?: string;
      description?: string;
      label?: string;
      name: string;
      required: boolean;
    };
    UpdateDefinitionRequest: {
      compose_yaml: string;
      env: string;
      expected_revision?: components["schemas"]["DefinitionRevision"];
      validate_after_save: boolean;
    };
    UpdateDefinitionResponse: {
      definition: components["schemas"]["StackDefinitionResponse"];
      job: components["schemas"]["Job"];
    };
    UpdatePasswordRequest: {
      current_password: string;
      /** @description New password length is measured in Unicode characters. */
      new_password: string;
    };
    UpdatePasswordResponse: {
      reauthentication_required: boolean;
      updated: boolean;
    };
    VolumeMount: {
      source: string;
      target: string;
    };
    WorkspaceRepairCapability: {
      reason?: string;
      recursive: boolean;
      supported: boolean;
    };
  };
  responses: {
    /** @description Upstream delivery failed. */
    ErrorBadGateway: {
      headers: {
        "X-Request-ID": components["headers"]["RequestID"];
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Request conflicts with current state. */
    ErrorConflict: {
      headers: {
        "X-Request-ID": components["headers"]["RequestID"];
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description File content or generated command output exceeds its bounded processing limit. */
    ErrorContentTooLarge: {
      headers: {
        "X-Request-ID": components["headers"]["RequestID"];
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Internal or session-storage failure. Authentication storage failures do not clear the existing cookie. */
    ErrorInternal: {
      headers: {
        "X-Request-ID": components["headers"]["RequestID"];
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Operation not allowed in current state. */
    ErrorInvalidState: {
      headers: {
        "X-Request-ID": components["headers"]["RequestID"];
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Resource not found. */
    ErrorNotFound: {
      headers: {
        "X-Request-ID": components["headers"]["RequestID"];
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Authentication required or invalid session. */
    ErrorUnauthorized: {
      headers: {
        "X-Request-ID": components["headers"]["RequestID"];
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description Validation failed. */
    ErrorValidationFailed: {
      headers: {
        "X-Request-ID": components["headers"]["RequestID"];
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: {
    /** @description Inclusive lower `requested_at` bound. RFC 3339 offsets are accepted and normalized to UTC. */
    AuditFrom?: string;
    /** @description Result filter. `failed` includes both failed and timed-out operations; `all` is equivalent to omitting the parameter. */
    AuditResult?: "all" | "succeeded" | "failed" | "cancelled" | "timed_out";
    /** @description Case-insensitive literal substring matched against the action and stack ID. */
    AuditSearch?: string;
    /** @description Exclusive upper `requested_at` bound. RFC 3339 offsets are accepted and normalized to UTC. */
    AuditTo?: string;
    Cursor?: string;
    JobId: string;
    Limit?: number;
    /** @description Optional caller correlation ID. Unsafe values are replaced by the server. */
    RequestID?: string;
    StackAction: "validate" | "up" | "down" | "stop" | "restart" | "pull" | "build" | "recreate";
    StackId: string;
  };
  requestBodies: never;
  headers: {
    /** @description Refreshed Stacklab session cookie with an expiry capped by the absolute session lifetime. */
    RefreshedSessionCookie: string;
    /** @description Correlates the response, structured request log, and any job started by the request. */
    RequestID: string;
  };
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  listAudit: {
    parameters: {
      query?: {
        stack_id?: string;
        q?: components["parameters"]["AuditSearch"];
        result?: components["parameters"]["AuditResult"];
        from?: components["parameters"]["AuditFrom"];
        to?: components["parameters"]["AuditTo"];
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
      };
    };
    responses: {
      /** @description Global audit log. */
      200: {
        content: {
          "application/json": components["schemas"]["AuditListResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      422: components["responses"]["ErrorValidationFailed"];
    };
  };
  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Login succeeded. */
      200: {
        headers: {
          "Set-Cookie": components["headers"]["RefreshedSessionCookie"];
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      500: components["responses"]["ErrorInternal"];
    };
  };
  logout: {
    responses: {
      /** @description Logout succeeded. */
      200: {
        content: {
          "application/json": components["schemas"]["LogoutResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      500: components["responses"]["ErrorInternal"];
    };
  };
  getConfigWorkspaceFile: {
    parameters: {
      query: {
        path: string;
      };
    };
    responses: {
      /** @description Config workspace file metadata and optional content. */
      200: {
        content: {
          "application/json": components["schemas"]["ConfigFileResponse"];
        };
      };
      /** @description Invalid path or path is not a file. */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      413: components["responses"]["ErrorContentTooLarge"];
    };
  };
  saveConfigWorkspaceFile: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigFileSaveRequest"];
      };
    };
    responses: {
      /** @description Config workspace file saved. */
      200: {
        content: {
          "application/json": components["schemas"]["ConfigFileSaveResponse"];
        };
      };
      /** @description Invalid path or parent directory shape. */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      /** @description Binary files are not editable in-browser. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      413: components["responses"]["ErrorContentTooLarge"];
    };
  };
  repairConfigWorkspacePermissions: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigRepairPermissionsRequest"];
      };
    };
    responses: {
      /** @description Config workspace ownership and owner access repaired. */
      200: {
        content: {
          "application/json": components["schemas"]["ConfigRepairPermissionsResponse"];
        };
      };
      /** @description Path escapes the managed config workspace. */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      /** @description Workspace permission repair is not configured. */
      501: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getConfigWorkspaceTree: {
    parameters: {
      query?: {
        path?: string;
      };
    };
    responses: {
      /** @description Directory-scoped config workspace listing. */
      200: {
        content: {
          "application/json": components["schemas"]["ConfigTreeResponse"];
        };
      };
      /** @description Invalid path or path is not a directory. */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
    };
  };
  getDockerAdminDaemonConfig: {
    responses: {
      /** @description Read-only Docker daemon config file view. */
      200: {
        content: {
          "application/json": components["schemas"]["DockerDaemonConfigResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  applyDockerAdminDaemonConfig: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DockerDaemonValidateRequest"];
      };
    };
    responses: {
      /** @description Started Docker daemon config apply workflow. */
      200: {
        content: {
          "application/json": components["schemas"]["JobEnvelopeResponse"];
        };
      };
      400: components["responses"]["ErrorValidationFailed"];
      401: components["responses"]["ErrorUnauthorized"];
      /** @description Current daemon.json is unreadable or invalid. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Docker daemon apply helper is not configured yet. */
      501: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  validateDockerAdminDaemonConfig: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DockerDaemonValidateRequest"];
      };
    };
    responses: {
      /** @description Managed Docker daemon config validation preview. */
      200: {
        content: {
          "application/json": components["schemas"]["DockerDaemonValidateResponse"];
        };
      };
      400: components["responses"]["ErrorValidationFailed"];
      401: components["responses"]["ErrorUnauthorized"];
      /** @description Current daemon.json is unreadable or invalid. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getDockerAdminOverview: {
    responses: {
      /** @description Docker daemon administration overview. */
      200: {
        content: {
          "application/json": components["schemas"]["DockerAdminOverviewResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  getDockerRegistryStatus: {
    responses: {
      /** @description Docker registry auth status for the effective DOCKER_CONFIG. */
      200: {
        content: {
          "application/json": components["schemas"]["DockerRegistryStatusResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  loginDockerRegistry: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DockerRegistryLoginRequest"];
      };
    };
    responses: {
      /** @description Started Docker registry login workflow. */
      200: {
        content: {
          "application/json": components["schemas"]["JobEnvelopeResponse"];
        };
      };
      400: components["responses"]["ErrorValidationFailed"];
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  logoutDockerRegistry: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DockerRegistryLogoutRequest"];
      };
    };
    responses: {
      /** @description Started Docker registry logout workflow. */
      200: {
        content: {
          "application/json": components["schemas"]["JobEnvelopeResponse"];
        };
      };
      400: components["responses"]["ErrorValidationFailed"];
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  commitGitWorkspace: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GitCommitRequest"];
      };
    };
    responses: {
      /** @description Local commit created for selected managed files. */
      200: {
        content: {
          "application/json": components["schemas"]["GitCommitResponse"];
        };
      };
      /** @description Invalid commit request or invalid path selection. */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      /** @description Commit cannot proceed due to conflicts, permissions, or no staged changes. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Git workspace is unavailable. */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getGitWorkspaceDiff: {
    parameters: {
      query: {
        path: string;
      };
    };
    responses: {
      /** @description Unified diff for one changed managed file. */
      200: {
        content: {
          "application/json": components["schemas"]["GitDiffResponse"];
        };
      };
      /** @description Invalid path or path outside managed roots. */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      413: components["responses"]["ErrorContentTooLarge"];
      /** @description Git workspace is unavailable. */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  pushGitWorkspace: {
    responses: {
      /** @description Current branch push result for configured upstream. */
      200: {
        content: {
          "application/json": components["schemas"]["GitPushResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      /** @description Upstream is missing or remote rejected the push. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Remote authentication failed. */
      502: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Git workspace is unavailable. */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getGitWorkspaceStatus: {
    responses: {
      /** @description Read-only Git status for the managed Stacklab workspace. */
      200: {
        content: {
          "application/json": components["schemas"]["GitWorkspaceStatusResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      413: components["responses"]["ErrorContentTooLarge"];
    };
  };
  /** @deprecated */
  getHealth: {
    responses: {
      /** @description Backward-compatible alias of `/ready`. */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      /** @description One or more required components are unavailable. */
      503: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  getHostMetrics: {
    parameters: {
      query?: {
        /** @description Return only history samples newer than this RFC3339 timestamp. Current sample is always returned. */
        since?: string;
      };
    };
    responses: {
      /** @description Host resource metrics with a short in-memory history. */
      200: {
        content: {
          "application/json": components["schemas"]["HostMetricsResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  getHostOverview: {
    responses: {
      /** @description Host and Stacklab runtime metadata. */
      200: {
        content: {
          "application/json": components["schemas"]["HostOverviewResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  getStacklabLogs: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
        level?: "debug" | "info" | "warn" | "error";
        q?: string;
        /** @description Include routine Stacklab HTTP access logs. Hidden by default to keep the host log panel focused on actionable events. */
        include_http?: boolean;
      };
    };
    responses: {
      /** @description Recent Stacklab service logs from journald. */
      200: {
        content: {
          "application/json": components["schemas"]["StacklabLogsResponse"];
        };
      };
      400: components["responses"]["ErrorValidationFailed"];
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  getJob: {
    parameters: {
      path: {
        jobId: components["parameters"]["JobId"];
      };
    };
    responses: {
      /** @description Job snapshot. */
      200: {
        content: {
          "application/json": components["schemas"]["JobDetailResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
    };
  };
  cancelJob: {
    parameters: {
      path: {
        jobId: components["parameters"]["JobId"];
      };
    };
    responses: {
      /** @description Job cancellation requested. */
      200: {
        content: {
          "application/json": components["schemas"]["JobEnvelopeResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      409: components["responses"]["ErrorInvalidState"];
    };
  };
  listJobEvents: {
    parameters: {
      path: {
        jobId: components["parameters"]["JobId"];
      };
    };
    responses: {
      /** @description Retained job events for replayable progress detail. */
      200: {
        content: {
          "application/json": components["schemas"]["JobEventsResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
    };
  };
  listActiveJobs: {
    responses: {
      /** @description Active jobs for global activity chrome. */
      200: {
        content: {
          "application/json": components["schemas"]["ActiveJobsResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  getLiveness: {
    responses: {
      /** @description Process liveness; succeeds while the HTTP process can serve requests. */
      200: {
        content: {
          "application/json": components["schemas"]["LivenessResponse"];
        };
      };
    };
  };
  listImageUpdates: {
    responses: {
      /** @description Cached per-image update states from the last check. */
      200: {
        content: {
          "application/json": components["schemas"]["ImageUpdatesResponse"];
        };
      };
    };
  };
  checkImageUpdates: {
    responses: {
      /** @description Image update check job accepted; runs detached. */
      200: {
        content: {
          "application/json": components["schemas"]["JobEnvelopeResponse"];
        };
      };
      /** @description Cross-origin request rejected. */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getMaintenanceImages: {
    parameters: {
      query?: {
        q?: string;
        usage?: "all" | "used" | "unused";
        origin?: "all" | "stack_managed" | "external";
      };
    };
    responses: {
      /** @description Maintenance image inventory. */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceImagesResponse"];
        };
      };
      400: components["responses"]["ErrorValidationFailed"];
      401: components["responses"]["ErrorUnauthorized"];
      /** @description Docker maintenance inventory is unavailable. */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getMaintenanceNetworks: {
    parameters: {
      query?: {
        q?: string;
        usage?: "all" | "used" | "unused";
        origin?: "all" | "stack_managed" | "external";
      };
    };
    responses: {
      /** @description Maintenance network inventory. */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceNetworksResponse"];
        };
      };
      400: components["responses"]["ErrorValidationFailed"];
      401: components["responses"]["ErrorUnauthorized"];
      /** @description Docker maintenance inventory is unavailable. */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createMaintenanceNetwork: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MaintenanceCreateNetworkRequest"];
      };
    };
    responses: {
      /** @description Docker network created. */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceCreateNetworkResponse"];
        };
      };
      400: components["responses"]["ErrorValidationFailed"];
      401: components["responses"]["ErrorUnauthorized"];
      /** @description Network already exists. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Docker maintenance actions are unavailable. */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteMaintenanceNetwork: {
    parameters: {
      path: {
        name: string;
      };
    };
    responses: {
      /** @description Docker network deleted. */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceDeleteNetworkResponse"];
        };
      };
      400: components["responses"]["ErrorValidationFailed"];
      401: components["responses"]["ErrorUnauthorized"];
      /** @description Docker network not found. */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Only unused external networks can be removed. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Docker maintenance actions are unavailable. */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  runMaintenancePrune: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MaintenancePruneRequest"];
      };
    };
    responses: {
      /** @description Prune job accepted. */
      200: {
        content: {
          "application/json": components["schemas"]["JobEnvelopeResponse"];
        };
      };
      400: components["responses"]["ErrorValidationFailed"];
      401: components["responses"]["ErrorUnauthorized"];
      /** @description Another global or stack maintenance job is already running. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getMaintenancePrunePreview: {
    parameters: {
      query?: {
        images?: boolean;
        build_cache?: boolean;
        stopped_containers?: boolean;
        volumes?: boolean;
      };
    };
    responses: {
      /** @description Prune preview summary. */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenancePrunePreviewResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      /** @description Docker prune preview is unavailable. */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  updateStacks: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MaintenanceUpdateStacksRequest"];
      };
    };
    responses: {
      /** @description Maintenance update job accepted. */
      200: {
        content: {
          "application/json": components["schemas"]["JobEnvelopeResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      /** @description One of the selected stacks is locked or invalid for update. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getMaintenanceVolumes: {
    parameters: {
      query?: {
        q?: string;
        usage?: "all" | "used" | "unused";
        origin?: "all" | "stack_managed" | "external";
      };
    };
    responses: {
      /** @description Maintenance volume inventory. */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceVolumesResponse"];
        };
      };
      400: components["responses"]["ErrorValidationFailed"];
      401: components["responses"]["ErrorUnauthorized"];
      /** @description Docker maintenance inventory is unavailable. */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  createMaintenanceVolume: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MaintenanceCreateVolumeRequest"];
      };
    };
    responses: {
      /** @description Docker volume created. */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceCreateVolumeResponse"];
        };
      };
      400: components["responses"]["ErrorValidationFailed"];
      401: components["responses"]["ErrorUnauthorized"];
      /** @description Volume already exists. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Docker maintenance actions are unavailable. */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  deleteMaintenanceVolume: {
    parameters: {
      path: {
        name: string;
      };
    };
    responses: {
      /** @description Docker volume deleted. */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceDeleteVolumeResponse"];
        };
      };
      400: components["responses"]["ErrorValidationFailed"];
      401: components["responses"]["ErrorUnauthorized"];
      /** @description Docker volume not found. */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Only unused external volumes can be removed. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Docker maintenance actions are unavailable. */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getMeta: {
    responses: {
      /** @description Application metadata. */
      200: {
        content: {
          "application/json": components["schemas"]["MetaResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  getReadiness: {
    responses: {
      /** @description Service and required component readiness. */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      /** @description One or more required components are unavailable. */
      503: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /** @description Return bounded, process-local service activity metrics. Counters reset when Stacklab restarts. */
  getServiceMetrics: {
    responses: {
      /** @description Current HTTP, job, WebSocket, and readiness metrics for this Stacklab process. */
      200: {
        content: {
          "application/json": components["schemas"]["ServiceMetricsResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  getSession: {
    responses: {
      /** @description Current session status. */
      200: {
        headers: {
          "Set-Cookie": components["headers"]["RefreshedSessionCookie"];
        };
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      500: components["responses"]["ErrorInternal"];
    };
  };
  getHostSettings: {
    responses: {
      /** @description Current Host dashboard settings. */
      200: {
        content: {
          "application/json": components["schemas"]["HostSettingsResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  updateHostSettings: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["HostSettingsRequest"];
      };
    };
    responses: {
      /** @description Host dashboard settings updated. */
      200: {
        content: {
          "application/json": components["schemas"]["HostSettingsResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  getMaintenanceSchedules: {
    responses: {
      /** @description Current scheduled maintenance policies. */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceSchedulesResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  updateMaintenanceSchedules: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MaintenanceSchedulesRequest"];
      };
    };
    responses: {
      /** @description Scheduled maintenance policies updated. */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceSchedulesResponse"];
        };
      };
      400: components["responses"]["ErrorValidationFailed"];
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  getNotificationSettings: {
    responses: {
      /** @description Current webhook notification settings. */
      200: {
        content: {
          "application/json": components["schemas"]["NotificationSettingsResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  updateNotificationSettings: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NotificationSettingsRequest"];
      };
    };
    responses: {
      /** @description Notification settings updated. */
      200: {
        content: {
          "application/json": components["schemas"]["NotificationSettingsResponse"];
        };
      };
      400: components["responses"]["ErrorValidationFailed"];
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  sendNotificationTest: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NotificationTestRequest"];
      };
    };
    responses: {
      /** @description Test notification delivered. */
      200: {
        content: {
          "application/json": components["schemas"]["NotificationTestResponse"];
        };
      };
      400: components["responses"]["ErrorValidationFailed"];
      401: components["responses"]["ErrorUnauthorized"];
      502: components["responses"]["ErrorBadGateway"];
    };
  };
  updatePassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePasswordRequest"];
      };
    };
    responses: {
      /** @description Password updated. */
      200: {
        content: {
          "application/json": components["schemas"]["UpdatePasswordResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      422: components["responses"]["ErrorValidationFailed"];
    };
  };
  applyStacklabUpdate: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["StacklabUpdateApplyRequest"];
      };
    };
    responses: {
      /** @description Started Stacklab self-update workflow. */
      200: {
        content: {
          "application/json": components["schemas"]["StacklabUpdateApplyResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      /** @description Update is not available or another self-update is already running. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Stacklab self-update is unavailable on this install or host. */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getStacklabUpdateOverview: {
    responses: {
      /** @description Stacklab self-update overview for the current install. */
      200: {
        content: {
          "application/json": components["schemas"]["StacklabUpdateOverviewResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  listStacks: {
    parameters: {
      query?: {
        q?: string;
        sort?: "name" | "state" | "last_action";
      };
    };
    responses: {
      /** @description Stack list and summary. */
      200: {
        content: {
          "application/json": components["schemas"]["StackListResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
    };
  };
  createStack: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateStackRequest"];
      };
    };
    responses: {
      /** @description Stack creation job accepted. */
      200: {
        content: {
          "application/json": components["schemas"]["JobEnvelopeResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      409: components["responses"]["ErrorConflict"];
      413: components["responses"]["ErrorContentTooLarge"];
      422: components["responses"]["ErrorValidationFailed"];
    };
  };
  getStack: {
    parameters: {
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
    responses: {
      /** @description Detailed stack view model. */
      200: {
        content: {
          "application/json": components["schemas"]["StackDetailResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
    };
  };
  deleteStack: {
    parameters: {
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteStackRequest"];
      };
    };
    responses: {
      /** @description Stack deletion job accepted. */
      202: {
        content: {
          "application/json": components["schemas"]["JobEnvelopeResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
    };
  };
  runStackAction: {
    parameters: {
      path: {
        stackId: components["parameters"]["StackId"];
        action: components["parameters"]["StackAction"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmptyObject"];
      };
    };
    responses: {
      /** @description Stack action job accepted. */
      200: {
        content: {
          "application/json": components["schemas"]["JobEnvelopeResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      /** @description Stack locked or invalid state. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  listStackAudit: {
    parameters: {
      query?: {
        q?: components["parameters"]["AuditSearch"];
        result?: components["parameters"]["AuditResult"];
        from?: components["parameters"]["AuditFrom"];
        to?: components["parameters"]["AuditTo"];
        cursor?: components["parameters"]["Cursor"];
        limit?: components["parameters"]["Limit"];
      };
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
    responses: {
      /** @description Per-stack audit log. */
      200: {
        content: {
          "application/json": components["schemas"]["AuditListResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      422: components["responses"]["ErrorValidationFailed"];
    };
  };
  getStackDefinition: {
    parameters: {
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
    responses: {
      /** @description Editable stack definition files. */
      200: {
        content: {
          "application/json": components["schemas"]["StackDefinitionResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      409: components["responses"]["ErrorInvalidState"];
      413: components["responses"]["ErrorContentTooLarge"];
    };
  };
  updateStackDefinition: {
    parameters: {
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateDefinitionRequest"];
      };
    };
    responses: {
      /** @description Definition save job accepted. */
      200: {
        content: {
          "application/json": components["schemas"]["UpdateDefinitionResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      409: components["responses"]["ErrorInvalidState"];
      413: components["responses"]["ErrorContentTooLarge"];
    };
  };
  getResolvedConfig: {
    parameters: {
      query?: {
        source?: "current" | "last_valid";
      };
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
    responses: {
      /** @description Resolved config or validation failure. */
      200: {
        content: {
          "application/json": components["schemas"]["ResolvedConfigResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      413: components["responses"]["ErrorContentTooLarge"];
    };
  };
  previewResolvedConfig: {
    parameters: {
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResolvedConfigPreviewRequest"];
      };
    };
    responses: {
      /** @description Draft resolved config preview or validation failure. */
      200: {
        content: {
          "application/json": components["schemas"]["ResolvedConfigResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      409: components["responses"]["ErrorInvalidState"];
      413: components["responses"]["ErrorContentTooLarge"];
    };
  };
  getStackWorkspaceFile: {
    parameters: {
      query: {
        path: string;
      };
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
    responses: {
      /** @description Auxiliary stack file metadata and optional content. */
      200: {
        content: {
          "application/json": components["schemas"]["StackWorkspaceFileResponse"];
        };
      };
      /** @description Invalid path or path is not a file. */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      /** @description Reserved, unreadable, or otherwise invalid stack workspace file. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      413: components["responses"]["ErrorContentTooLarge"];
    };
  };
  saveStackWorkspaceFile: {
    parameters: {
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StackWorkspaceFileSaveRequest"];
      };
    };
    responses: {
      /** @description Auxiliary stack file saved. */
      200: {
        content: {
          "application/json": components["schemas"]["StackWorkspaceFileSaveResponse"];
        };
      };
      /** @description Invalid path or parent directory shape. */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      /** @description Reserved, binary, conflicted, or unwritable stack workspace file. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      413: components["responses"]["ErrorContentTooLarge"];
    };
  };
  repairStackWorkspacePermissions: {
    parameters: {
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StackRepairPermissionsRequest"];
      };
    };
    responses: {
      /** @description Stack workspace ownership and owner access repaired. */
      200: {
        content: {
          "application/json": components["schemas"]["StackRepairPermissionsResponse"];
        };
      };
      /** @description Path escapes the managed stack workspace. */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      /** @description Workspace permission repair is not configured. */
      501: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getStackWorkspaceTree: {
    parameters: {
      query?: {
        path?: string;
      };
      path: {
        stackId: components["parameters"]["StackId"];
      };
    };
    responses: {
      /** @description Directory-scoped auxiliary stack workspace listing. */
      200: {
        content: {
          "application/json": components["schemas"]["StackWorkspaceTreeResponse"];
        };
      };
      /** @description Invalid path or path is not a directory. */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: components["responses"]["ErrorUnauthorized"];
      404: components["responses"]["ErrorNotFound"];
      /** @description Stack workspace path is not readable by Stacklab. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  listTemplates: {
    responses: {
      /** @description Curated stack templates (operator-provided or built-in). */
      200: {
        content: {
          "application/json": components["schemas"]["TemplatesResponse"];
        };
      };
    };
  };
}
